version: '3.1'
services:
  odoo-stack:
    container_name: odoo-stack
    build:
      context: .
      dockerfile: dockerfile/odoo.Dockerfile
    volumes:
      # - ./create_odoo_db_interactive.sh:/usr/local/bin/create_odoo_db_interactive.sh
      - ./addons-extra:/mnt/addons-extra
      - /home/bjit/odoo-18.0+e.20241126/odoo/addons:/mnt/enterprise_addons
      - ./odoo-config:/etc/odoo
      - odoo-web-data:/var/lib/odoo

    ports:
      - 8069:8069

    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo

    depends_on:

      - database-stack

    restart: always
  
  database-stack:
    container_name: database-stack
    image: postgres:latest
    volumes:

      - database-stack-data:/var/lib/postgresql/data/pgdata

    ports:

      - 5432:5432

    # command: -p 5433
    environment:

      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

    restart: always

  pgadmin-stack:
    container_name: pgadmin-stack
    image: dpage/pgadmin4:5.4
    volumes:

      - pgadmin-data:/var/lib/pgadmin

    ports:

      - 8080:80

    links:

      - "database-stack:pgsql-server"

    environment:
      PGADMIN_DEFAULT_EMAIL: shane@odootraining.ddns.net
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    depends_on:

      - database-stack

    restart: always
    
  nginx-stack:
    container_name: nginx-stack
    build:
      context: ./dockerfile
      dockerfile: nginx.Dockerfile

    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./nginx-ssl:/etc/nginx/ssl 

    ports:

      - 80:80   #non secure
      - 443:443 #ssl

    depends_on:

      - odoo-stack

    restart: always

volumes:
  odoo-web-data:
  database-stack-data:
  pgadmin-data: